package recipe

import (
	"fmt"
	"sort"
	"strings"
)

// baseSystem is installed into every image. Keeping the list short and fixed
// means a repository's own apt step is visible as a diff against this, rather
// than buried in it.
var baseSystem = []string{"ca-certificates", "curl", "git", "make", "pkg-config", "unzip", "xz-utils"}

// cacheDirs are the per-ecosystem paths that get a shared named volume, so a
// second repository in the same language starts warm. Warm caches are what
// make the network-off verification run realistic rather than merely strict.
var cacheDirs = map[string]struct {
	vol, path string
	env       map[string]string
}{
	// GOTOOLCHAIN=auto, not local. A base image's Go is routinely older than
	// the clone's go.mod requires -- cli/cli's own devcontainer pins 1.26
	// while its go.mod asks for 1.27 -- and under `local` that is a hard
	// "go.mod requires go >= 1.27.0" before a single test runs. Under `auto`
	// the toolchain downloads once during the networked install phase into
	// GOPATH, which is this named volume, and the network-off verification
	// run then finds it already there.
	"go": {"ossp-cache-go", "/cache/go", map[string]string{
		"GOPATH": "/cache/go", "GOMODCACHE": "/cache/go/pkg/mod", "GOCACHE": "/cache/go/build",
		"GOFLAGS": "-mod=mod", "GOTOOLCHAIN": "auto",
	}},
	"python": {"ossp-cache-pip", "/cache/pip", map[string]string{
		"PIP_CACHE_DIR": "/cache/pip", "UV_CACHE_DIR": "/cache/pip/uv",
		"PIP_DISABLE_PIP_VERSION_CHECK": "1", "PYTHONDONTWRITEBYTECODE": "1",
	}},
	"node": {"ossp-cache-npm", "/cache/npm", map[string]string{
		"npm_config_cache": "/cache/npm", "COREPACK_ENABLE_DOWNLOAD_PROMPT": "0",
	}},
	"rust": {"ossp-cache-cargo", "/cache/cargo", map[string]string{
		"CARGO_HOME": "/cache/cargo",
	}},
	"pixi": {"ossp-cache-pixi", "/cache/pixi", map[string]string{
		"PIXI_CACHE_DIR": "/cache/pixi",
	}},
}

// rootOwnedInstallDirs repairs the one thing that breaks every recipe in an
// ecosystem whose package manager installs into a root-owned system directory.
//
// The container runs as uid 1000 -- it has to, or every file the build touches
// comes back to the host owned by root. But `pip install -e .` and `uv pip
// install --system` both target the base image's site-packages, and
// `npm install -g` targets its global prefix, and both are root-owned in the
// official images. The result is EACCES before a single test runs, which is
// indistinguishable from a broken patch. Ownership is handed over at build
// time, while the Dockerfile is still root.
var rootOwnedInstallDirs = map[string]string{
	"python": `RUN d="$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')" \
 && mkdir -p "$d" \
 && chown -R 1000:1000 "$d" "$(dirname "$(command -v python3)")"`,
	"node": `RUN d="$(npm prefix -g)" \
 && mkdir -p "$d/lib/node_modules" "$d/bin" \
 && chown -R 1000:1000 "$d/lib/node_modules" "$d/bin"`,
}

// Dockerfile renders the image. The build context is manifests only, never the
// source tree: the clone is bind-mounted at run time, so one image serves
// every branch and the agent's edits land on the host checkout directly.
// Copying an 895 MB checkout into a build context to achieve the same thing is
// the mistake this avoids.
func (r Recipe) Dockerfile() string {
	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f+"\n", a...) }

	p("# Generated by osspipeline. Do not edit.")
	p("# repo:     %s", r.Repo)
	p("# source:   %s", r.Source)
	for _, e := range r.Evidence {
		p("# evidence: %s", e)
	}
	p("FROM %s", r.BaseImage)
	p("ENV DEBIAN_FRONTEND=noninteractive LANG=C.UTF-8 CI=1")
	p("")

	pkgs := dedupe(append(append([]string{}, baseSystem...), r.System...))
	sort.Strings(pkgs)
	p("RUN apt-get update \\")
	p(" && apt-get install -y --no-install-recommends \\")
	for _, pk := range pkgs {
		p("      %s \\", pk)
	}
	p(" && rm -rf /var/lib/apt/lists/*")
	p("")

	env := map[string]string{}
	var vols []string
	for _, l := range r.ecosystems() {
		cd, ok := cacheDirs[l]
		if !ok {
			continue
		}
		vols = append(vols, cd.path)
		for k, v := range cd.env {
			env[k] = v
		}
	}
	if len(env) > 0 {
		p("ENV \\")
		ks := sortedKeys(env)
		for i, k := range ks {
			tail := " \\"
			if i == len(ks)-1 {
				tail = ""
			}
			p("    %s=%s%s", k, env[k], tail)
		}
		p("")
	}

	// uid 1000 must exist and own the cache mounts. Some bases already have
	// it -- node images ship `node` at 1000, devcontainer images ship
	// `vscode` -- and useradd would fail there, so this is conditional.
	sort.Strings(vols)
	p("RUN if ! getent passwd 1000 >/dev/null 2>&1; then \\")
	p("      getent group 1000 >/dev/null 2>&1 || groupadd -g 1000 ossp; \\")
	p("      useradd -u 1000 -g 1000 -m -s /bin/bash ossp; \\")
	p("    fi \\")
	if len(vols) > 0 {
		p(" && mkdir -p %s \\", strings.Join(vols, " "))
		p(" && chown -R 1000:1000 %s \\", strings.Join(vols, " "))
	}
	p(" && mkdir -p /work && chown 1000:1000 /work")
	p("")
	for _, l := range r.ecosystems() {
		if fix, ok := rootOwnedInstallDirs[l]; ok {
			p("%s", fix)
			p("")
		}
	}
	p("USER 1000:1000")
	p("WORKDIR /work")
	return b.String()
}

// ecosystems returns the languages this recipe touches, deterministically.
func (r Recipe) ecosystems() []string {
	var out []string
	for _, t := range r.Tools {
		out = append(out, t.Lang)
	}
	for _, m := range r.MaskVolumes {
		switch m {
		case ".venv", ".pytest_cache":
			out = append(out, "python")
		case "node_modules":
			out = append(out, "node")
		case "target":
			out = append(out, "rust")
		case ".pixi":
			out = append(out, "pixi")
		}
	}
	out = dedupe(out)
	sort.Strings(out)
	return out
}

// Volumes returns the named-volume mounts for a session: shared per-ecosystem
// caches, plus per-repository build directories mounted *over* the clone so
// build output never lands in the bind-mounted checkout.
func (r Recipe) Volumes() map[string]string {
	out := map[string]string{}
	for _, l := range r.ecosystems() {
		if cd, ok := cacheDirs[l]; ok {
			out[cd.vol] = cd.path
		}
	}
	slug := Slug(r.Repo)
	for _, m := range r.MaskVolumes {
		name := fmt.Sprintf("ossp-build-%s-%s", slug, strings.ReplaceAll(strings.TrimPrefix(m, "."), "/", "-"))
		out[name] = "/work/" + m
	}
	return out
}

// Slug turns owner/name into a docker-safe identifier, matching the convention
// the clone directories already use.
func Slug(repo string) string {
	s := strings.ReplaceAll(repo, "/", "__")
	var b strings.Builder
	for _, c := range s {
		switch {
		case c >= 'a' && c <= 'z', c >= '0' && c <= '9', c == '_', c == '-', c == '.':
			b.WriteRune(c)
		case c >= 'A' && c <= 'Z':
			b.WriteRune(c + 32)
		default:
			b.WriteByte('-')
		}
	}
	return b.String()
}

// ImageTag names the built image. The tag is a digest of the Dockerfile, so a
// changed recipe never reuses a stale image and an unchanged one never
// rebuilds.
func (r Recipe) ImageTag() string {
	return fmt.Sprintf("ossp/%s:%s", Slug(r.Repo), shortHash(r.Dockerfile()))
}

// shortHash is FNV-1a. Not a security boundary -- it only has to change when
// the Dockerfile changes.
func shortHash(s string) string {
	var h uint64 = 14695981039346656037
	for i := 0; i < len(s); i++ {
		h ^= uint64(s[i])
		h *= 1099511628211
	}
	return fmt.Sprintf("%012x", h&0xffffffffffff)
}
